/*

========================= COMPETENCIAS =========================

*/

insert into CaracteristicasDevelop.competencias (nombre,descripcion) values
("Competencia en Acrobacias","Permite el uso de tu bonificador de competencia en esta habilidad"),
("Competencia en Atletismo","Permite el uso de tu bonificador de competencia en esta habilidad"),
("Competencia en Conocimiento Arcano","Permite el uso de tu bonificador de competencia en esta habilidad"),
("Competencia en Engaño","Permite el uso de tu bonificador de competencia en esta habilidad"),
("Competencia en Historia","Permite el uso de tu bonificador de competencia en esta habilidad"),
("Competencia en Interpretación","Permite el uso de tu bonificador de competencia en esta habilidad"),
("Competencia en Intimidación","Permite el uso de tu bonificador de competencia en esta habilidad"),
("Competencia en Investigación","Permite el uso de tu bonificador de competencia en esta habilidad"),
("Competencia en Juego de Manos","Permite el uso de tu bonificador de competencia en esta habilidad"),
("Competencia en Medicina","Permite el uso de tu bonificador de competencia en esta habilidad"),
("Competencia en Naturaleza","Permite el uso de tu bonificador de competencia en esta habilidad"),
("Competencia en Percepción","Permite el uso de tu bonificador de competencia en esta habilidad"),
("Competencia en Perspicacia","Permite el uso de tu bonificador de competencia en esta habilidad"),
("Competencia en Persuasión","Permite el uso de tu bonificador de competencia en esta habilidad"),
("Competencia en Religión","Permite el uso de tu bonificador de competencia en esta habilidad"),
("Competencia en Sigilo","Permite el uso de tu bonificador de competencia en esta habilidad"),
("Competencia en Supervivencia","Permite el uso de tu bonificador de competencia en esta habilidad"),
("Competencia en Trato con Animales","Permite el uso de tu bonificador de competencia en esta habilidad"),
("Competencia con Armas Sencillas","Te permite usar cualquier arma catalogada como arma Sencilla"),
("Competencia con Armas Marciales","Te permite usar cualquir arma catalogada como arma Marcial"),
("Competencia con Armaduras Ligeras","Te permite usar cualquier armadura catalogada como Ligera"),
("Competencia con Armaduras Medias","Te permite usar cualquier armadura catalogada como Media"),
("Competencia con Armaduras Pesadas","Te permite usar cualquier armadura catalogada como Pesada"),
("Competencia con Escudos","Te permite usar Escudos"),
("Competencia con Instrumentos","Te permite el uso de un instrumento de tu elección y no te cuesta aprender a usar otros"),
("Competencia con Herramientas de Herrero","Te permite el uso de estas herramientas asi como el poder crear, mejorar o reparar objetos con ellas"),
("Competencia con Herramientas de Alquimia","Te permite el uso de estas herramientas asi como el poder crear, mejorar o repararobjetos con ellas"),
("Competencia con Herramientas de Cervecero","Te permite el uso de estas herramientas asi como el poder crear, mejorar o reparar objetos con ellas"),
("Competencia con Herramientas de Caligrafía","Te permite el uso de estas herramientas asi como el poder crear, mejorar o reparar objetos con ellas"),
("Competencia con Herramientas de Carpintero","Te permite el uso de estas herramientas asi como el poder crear, mejorar o reparar objetos con ellas"),
("Competencia con Herramientas de Cartógrafo","Te permite el uso de estas herramientas asi como el poder crear, mejorar o reparar objetos con ellas"),
("Competencia con Herramientas de Zapatero","Te permite el uso de estas herramientas asi como el poder crear, mejorar o reparar objetos con ellas"),
("Competencia con Herramientas de Cocina","Te permite el uso de estas herramientas asi como el poder crear, mejorar o reparar objetos con ellas"),
("Competencia con Herramientas de Disfraz","Te permite el uso de estas herramientas para disfrazarte o disfrazar a otros de forma que no llame la atención"),
("Competencia con Juegos","Sabes jugar a cualquier tipo de juego de Taberna (dados,carta,etc...)"),
("Competencia con Herramientas de Falsificación","Te permite el uso de estas herramientas asi como el poder crear, mejorar o reparar objetos con ellas"),
("Competencia con Herramientas de Herboristeria","Te permite el uso de estas herramientas asi como el poder crear, mejorar o reparar objetos con ellas"),
("Competencia con Herramientas de Joyero","Te permite el uso de estas herramientas asi como el poder crear, mejorar o reparar objetos con ellas"),
("Competencia con Kit de Venenos","Te permite el uso de estas herramientas asi como el poder crear, mejorar venenos con ellas"),
("Competencia con Herramientas de Ladrón","Te permite el uso de estas herramientas, como por ejemplo, para poder forjar cerraduras"),
("Competencia con Vehiculos Terrestes","Te permite manejar correctamente cualquier tipo de vehiculo Terreste"),
("Competencia con Vehiculos Marino","Te permite manejar correctamente cualquier tipo de vehiculo Marino"),
("Competencia en Tiradas de Salvación de Fuerza","Te permite usar Tiradas de Salvación de esta caracteristica"),
("Competencia en Tiradas de Salvación de Destreza","Te permite usar Tiradas de Salvación de esta caracteristica"),
("Competencia en Tiradas de Salvación de Constitución","Te permite usar Tiradas de Salvación de esta caracteristica"),
("Competencia en Tiradas de Salvación de Inteligencia","Te permite usar Tiradas de Salvación de esta caracteristica"),
("Competencia en Tiradas de Salvación de Sabiduría","Te permite usar Tiradas de Salvación de esta caracteristica"),
("Competencia en Tiradas de Salvación de Carisma","Te permite usar Tiradas de Salvación de esta caracteristica");